build.gradle, src/main/java/jungmo/server/global/HomeController.java, src/main/java/jungmo/server/global/config/SecurityConfig.java, src/main/java/jungmo/server/global/config/SwaggerConfig.java
=> feat: 스웨거 설정

src/main/java/jungmo/server/global/config/SecurityConfig.java
=> chore: 인증경로 추가 #8

build.gradle, src/main/java/jungmo/server/global/config/CorsConfig.java, src/main/java/jungmo/server/global/config/SecurityConfig.java, src/main/java/jungmo/server/global/config/SwaggerConfig.java
=> feat: Cors 설정 #8

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringUserController.java, src/main/java/jungmo/server/domain/controller/UserController.java, src/main/java/jungmo/server/domain/dto/request/GatheringDto.java, src/main/java/jungmo/server/domain/dto/request/UserCodeDto.java, src/main/java/jungmo/server/domain/dto/response/GatheringListResponseDto.java, src/main/java/jungmo/server/domain/dto/response/GatheringResponseDto.java, src/main/java/jungmo/server/domain/entity/Gathering.java, src/main/java/jungmo/server/domain/entity/GatheringUser.java, src/main/java/jungmo/server/domain/repository/GatheringRepository.java, src/main/java/jungmo/server/domain/repository/GatheringUserRepository.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java, src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/result/ResultCode.java
=> 마이페이지 정보조회 API 및 모임관련 API수정

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringUserController.java, src/main/java/jungmo/server/domain/dto/response/GatheringResponseDto.java, src/main/java/jungmo/server/domain/entity/Gathering.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java
restapi 네이밍 규칙에 맞게 수정하고
서비스단 트랜잭션을 따로 관리하도록 한다
=> fix: api 수정 #28

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringLocationController.java, src/main/java/jungmo/server/domain/controller/GatheringLocationSwaggerController.java, src/main/java/jungmo/server/domain/controller/GatheringSwaggerController.java, src/main/java/jungmo/server/domain/controller/UserController.java, src/main/java/jungmo/server/domain/controller/UserSwaggerController.java, src/main/java/jungmo/server/domain/dto/request/PasswordRequest.java, src/main/java/jungmo/server/domain/entity/User.java, src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/error/ErrorCode.java, src/main/java/jungmo/server/global/result/ResultCode.java
=> feat: 비밀번호 변경

src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/auth/controller/AuthController.java, src/main/java/jungmo/server/global/auth/controller/AuthSwaggerController.java, src/main/java/jungmo/server/global/error/ErrorCode.java
=> feat: 비밀번호 변경시 소셜로그인 검증 추가

src/main/java/jungmo/server/global/auth/controller/AuthController.java, src/main/java/jungmo/server/global/auth/service/AuthService.java, src/main/java/jungmo/server/global/error/ErrorCode.java, src/main/java/jungmo/server/global/filter/JwtAuthenticationFilter.java, src/main/java/jungmo/server/global/result/ResultCode.java
=> feat: 로그아웃

src/main/java/jungmo/server/global/auth/controller/AuthController.java, src/main/java/jungmo/server/global/auth/controller/AuthSwaggerController.java, src/main/java/jungmo/server/global/auth/service/RedisService.java
=> feat: 로그아웃 스웨거 설정

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringLocationController.java, src/main/java/jungmo/server/domain/controller/UserController.java, src/main/java/jungmo/server/domain/dto/request/PasswordRequest.java, src/main/java/jungmo/server/domain/entity/User.java, src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/auth/controller/AuthController.java, src/main/java/jungmo/server/global/auth/controller/AuthSwaggerController.java, src/main/java/jungmo/server/global/auth/service/AuthService.java, src/main/java/jungmo/server/global/auth/service/KakaoService.java, src/main/java/jungmo/server/global/auth/service/PrincipalDetails.java, src/main/java/jungmo/server/global/error/ErrorCode.java, src/main/java/jungmo/server/global/oauth2/service/CustomOAuth2UserService.java, src/main/java/jungmo/server/global/result/ResultCode.java, src/main/java/jungmo/server/global/util/JwtTokenProvider.java
=> feat: 탈퇴기능 구현

src/main/java/jungmo/server/domain/controller/UserSwaggerController.java
=> feat: 탈퇴기능 스웨거 설정

src/main/java/jungmo/server/domain/dto/request/LocationRequest.java, src/main/java/jungmo/server/domain/dto/response/LocationResponse.java, src/main/java/jungmo/server/domain/entity/Gathering.java, src/main/java/jungmo/server/domain/entity/GatheringLocation.java, src/main/java/jungmo/server/domain/entity/Location.java, src/main/java/jungmo/server/domain/entity/User.java, src/main/java/jungmo/server/domain/repository/GatheringLocationRepository.java, src/main/java/jungmo/server/domain/repository/LocationRepository.java, src/main/java/jungmo/server/domain/service/LocationService.java
=> fix: 장소 객체 컬럼 수정 #43

src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/auth/service/AuthService.java, src/main/java/jungmo/server/global/oauth2/handler/CustomOAuth2SuccessHandler.java, src/main/java/jungmo/server/global/oauth2/service/CustomOAuth2UserService.java
소셜 로그인 로컬테스트
소셜로그인 할때 유저코드 부여하도록 로직 수정
=> fix: 소셜 로그인 로직 수정

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringLocationController.java, src/main/java/jungmo/server/domain/controller/UserController.java, src/main/java/jungmo/server/domain/controller/UserSwaggerController.java, src/main/java/jungmo/server/domain/dto/response/GatheringResponse.java, src/main/java/jungmo/server/domain/repository/GatheringLocationRepository.java, src/main/java/jungmo/server/domain/repository/GatheringRepository.java, src/main/java/jungmo/server/domain/repository/GatheringUserRepository.java, src/main/java/jungmo/server/domain/repository/LocationRepository.java, src/main/java/jungmo/server/domain/repository/UserRepository.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java, src/main/java/jungmo/server/global/auth/service/CustomUserDetailsService.java, src/main/java/jungmo/server/global/config/SecurityConfig.java, src/main/java/jungmo/server/global/filter/JwtAuthenticationFilter.java, src/main/java/jungmo/server/global/util/JwtTokenProvider.java
=> fix: 모임 조회 시 권한 반환 #43

src/main/java/jungmo/server/domain/dto/request/LocationRequest.java, src/main/java/jungmo/server/domain/dto/response/LocationResponse.java, src/main/java/jungmo/server/domain/entity/Location.java, src/main/java/jungmo/server/domain/repository/GatheringLocationRepository.java, src/main/java/jungmo/server/domain/service/EmailService.java, src/main/java/jungmo/server/domain/service/GatheringLocationService.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java, src/main/java/jungmo/server/domain/service/LocationService.java
=> fix: 장소저장 placeId만 저장할 수 있도록 수정 #43

src/main/java/jungmo/server/domain/provider/GatheringDataProvider.java, src/main/java/jungmo/server/domain/provider/GatheringLocationDataProvider.java, src/main/java/jungmo/server/domain/provider/UserDataProvider.java, src/main/java/jungmo/server/domain/service/GatheringLocationService.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java, src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/domain/service/policy/GatheringUserPolicy.java
=> refactor: 서비스 책임분리#43

build.gradle, src/main/java/jungmo/server/domain/controller/SseController.java, src/main/java/jungmo/server/domain/controller/SseSwaggerController.java, src/main/java/jungmo/server/domain/dto/response/EventPayload.java, src/main/java/jungmo/server/domain/dto/response/NotificationResponse.java, src/main/java/jungmo/server/domain/entity/Notification.java, src/main/java/jungmo/server/domain/event/NotificationEvent.java, src/main/java/jungmo/server/domain/event/NotificationEventListener.java, src/main/java/jungmo/server/domain/repository/EmitterRepository.java, src/main/java/jungmo/server/domain/repository/NotificationRepository.java, src/main/java/jungmo/server/domain/service/GatheringNotificationService.java, src/main/java/jungmo/server/domain/service/GatheringUserService.java, src/main/java/jungmo/server/domain/service/NotificationService.java, src/main/java/jungmo/server/domain/service/SseEmitterService.java, src/main/java/jungmo/server/global/config/AsyncConfig.java, src/main/java/jungmo/server/global/config/S3Config.java
=> feat:SSE이용해 모임 초대시 알림기능 구현 #43

src/main/java/jungmo/server/domain/controller/SseController.java, src/main/java/jungmo/server/domain/controller/SseSwaggerController.java, src/main/java/jungmo/server/domain/dto/request/NotificationReadRequest.java, src/main/java/jungmo/server/domain/dto/request/NotificationRequest.java, src/main/java/jungmo/server/domain/dto/response/EventPayload.java, src/main/java/jungmo/server/domain/dto/response/NotificationResponse.java, src/main/java/jungmo/server/domain/entity/Notification.java, src/main/java/jungmo/server/domain/event/NotificationEventListener.java, src/main/java/jungmo/server/domain/repository/NotificationRepository.java, src/main/java/jungmo/server/domain/service/NotificationService.java, src/main/java/jungmo/server/global/result/ResultCode.java
=> 알림 삭제, 읽음 처리 구현 #43

src/main/java/jungmo/server/domain/dto/request/GatheringRequest.java, src/main/java/jungmo/server/domain/dto/request/GatheringUserRequest.java, src/main/java/jungmo/server/domain/dto/request/NotificationRequest.java, src/main/java/jungmo/server/domain/dto/request/PasswordRequest.java, src/main/java/jungmo/server/domain/dto/request/PasswordResetRequest.java, src/main/java/jungmo/server/domain/dto/request/PositionRequest.java, src/main/java/jungmo/server/domain/dto/request/ResetPasswordRequest.java, src/main/java/jungmo/server/domain/dto/request/UserCodeRequest.java, src/main/java/jungmo/server/domain/dto/request/UserRequest.java
=> refactor: 요청 데이터 유효성 검증 수정 #43

src/main/java/jungmo/server/domain/controller/GatheringController.java, src/main/java/jungmo/server/domain/controller/GatheringSwaggerController.java, src/main/java/jungmo/server/domain/controller/UserController.java, src/main/java/jungmo/server/domain/controller/UserSwaggerController.java, src/main/java/jungmo/server/domain/dto/response/GatheringListResponse.java, src/main/java/jungmo/server/domain/provider/UserDataProvider.java, src/main/java/jungmo/server/domain/repository/GatheringRepository.java, src/main/java/jungmo/server/domain/repository/UserRepository.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/domain/service/UserService.java
#43 
- 모임 목록 반환시 만나는장소 정보 반환, 받은 날짜가 모임의 startDate,endDate사이에 들어가는 모임 모두 조회
- 유저코드 검색시 와일드카드 사용해 추출된 데이터들 List로 반환
=> refactor: 모임 수정

src/main/java/jungmo/server/domain/service/SseEmitterService.java
=> remove: 연결알림 삭제

src/main/java/jungmo/server/domain/dto/response/NotificationResponse.java, src/main/java/jungmo/server/domain/entity/Notification.java, src/main/java/jungmo/server/domain/repository/GatheringUserRepository.java, src/main/java/jungmo/server/domain/service/GatheringNotificationService.java, src/main/java/jungmo/server/global/config/CorsConfig.java, src/main/java/jungmo/server/global/error/ErrorCode.java
- 알림 목록에 제목,모임 만든유저의 프로필이미지 추가
- cors 수정
=> refactor: 알림 목록에 제목,모임 만든유저의 프로필이미지 추가

.gitignore, src/main/java/jungmo/server/domain/controller/ChatMessageController.java, src/main/java/jungmo/server/domain/controller/ChattingRoomController.java, src/main/java/jungmo/server/domain/controller/ChattingRoomSwaggerController.java, src/main/java/jungmo/server/domain/dto/request/chat/ChattingMessageRequest.java, src/main/java/jungmo/server/domain/dto/response/UserChattingRoomsResponse.java, src/main/java/jungmo/server/domain/entity/ChattingMessage.java, src/main/java/jungmo/server/domain/entity/MessageType.java, src/main/java/jungmo/server/domain/provider/ChattingRoomProvider.java, src/main/java/jungmo/server/domain/repository/chat/ChattingRoomRepository.java, src/main/java/jungmo/server/domain/repository/chat/ChattingRoomRepositoryCustom.java, src/main/java/jungmo/server/domain/repository/chat/ChattingRoomRepositoryImpl.java, src/main/java/jungmo/server/domain/service/ChattingRoomService.java, src/main/java/jungmo/server/domain/service/GatheringService.java, src/main/java/jungmo/server/global/auth/service/S3Service.java, src/main/java/jungmo/server/global/config/SecurityConfig.java, src/main/java/jungmo/server/global/config/WebSocketConfig.java, src/main/java/jungmo/server/global/filter/JwtAuthenticationFilter.java, src/main/java/jungmo/server/global/interceptor/ChatHandler.java, src/main/java/jungmo/server/global/result/ResultCode.java, src/main/java/jungmo/server/global/util/jwt/JwtProvider.java, src/main/java/jungmo/server/global/util/jwt/WebSocketTokenProvider.java
WebScoketConfig -> CORS 도메인 front.jungmoserver.shop 허용
ChatHandler -> CONNECT시 Jwt 토큰 검증 후 Authenication user 객체 담아주고, ConnectedEventHandler에서 Redis에 담아주기
ChattingRoomController -> 자신이 조회한 채팅방 리스트 조회
=> feat: stomp 초기 설정

src/main/java/jungmo/server/domain/service/UserService.java, src/main/java/jungmo/server/global/auth/controller/AuthController.java, src/main/java/jungmo/server/global/auth/controller/AuthSwaggerController.java, src/main/java/jungmo/server/global/auth/dto/response/AccessTokenResponse.java, src/main/java/jungmo/server/global/auth/dto/response/UserLoginResponse.java, src/main/java/jungmo/server/global/auth/service/AuthService.java, src/main/java/jungmo/server/global/oauth2/handler/CustomOAuth2SuccessHandler.java
- 클라이언트에서 액세스토큰 global state로 관리할 수 있도록 액세스토큰 바디로 반환
=> refactor: 로그인, 회원가입, 토큰 리프레시 시 액세스토큰 바디로 반환
